blog/urls.py
from django.conf.urls import url
from django.urls import path
from .views import PostList, post_detail, PostCreate

urlpatterns =[
    path('', PostList.as_view(),  # here using a dictionary to override the base template of our view
         name='blog_post_list'), # as_view() method is provided by the inheritance of the View superclass and ensures that the proper method in our Class Based View is called,,as_view() will direct Django to get() method
    url(r'^(?P<year>\d{4})/' r'(?P<month>\d{1,2})/' r'(?P<slug>[\w\-]+)/$', # year has 4 digits,a month has 1 or 2 digits,and finally our slug is set of alphanumeric(w),underscore(-) or dash charchters
        post_detail,name='blog_post_detail'), # pass the parameter year,month and slug to view function,& this one came from user input,,year,month,slug value which one user given pass onto view function
    path('create/',PostCreate.as_view(),name='blog_post_create'),
]

# as_view() returns a view(a method on the instance of PostList),its main purpose is to define a function that acts as
# an intermediary view,it receives all the data,figures out which CBV method to call,and then passes all the data to
# that method

organizer/urls.py
from django.conf.urls import url
from .views import StartupCreate,TagCreate,homepage, tag_detail,tag_list, startup_list, startup_detail,tag_create
from django.urls import path

urlpatterns = [
    path('tag/',tag_list,name='organizer_tag_list'),
    # path('tag/create/',tag_create,name='organizer_tag_create'), # we must give precedence tag_create over tag_detail url,if we use tag_create before tag_detail then running server requisting tag/create/ will call tag_detail view and shows http 404 error('create' tag does not exist)
    path('tag/create/',TagCreate.as_view(),name='organizer_tag_create'),
    url(r'^tag/(?P<slug>[\w\-]+)/$',tag_detail,name='organizer_tag_detail'), # here (?P<name>pattern),use '+' character to match at least one character,'\w' will match alphanumeric characters and the underscore(-), ^=start symbol,$=end symbol
    path('startup/',startup_list,name='organizer_startup_list'),
    url(r'^startup/(?P<slug>[\w\-]+)/$',startup_detail,name='organizer_startup_detail'),
    path('startup/create/',StartupCreate.as_view(),name='organizer_startup_create'),
]

suorganizer/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.urls import path
from .views import redirect_root
from organizer.views import homepage,tag_detail
from organizer import urls as organizer_urls
from blog.views import PostList

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',redirect_root), # in home url the url goes into automatically blog url for this  method
    # path('', include(organizer_urls)),
    path('organizer/',include('organizer.urls')),
    path('blog/',include('blog.urls')),
]

organizer/models.py
from django.db import models
from django.urls import reverse


class Tag(models.Model):
    name = models.CharField(max_length=31,unique=True)
    slug = models.SlugField(max_length=31,unique=True,help_text='A label for URL config') # help text is quick information what is slug is

    def __str__(self):
        return self.name.title() # here using title for captalizing the name field,representation of object in the interpreter and admin

    class Meta:
        ordering = ['name']  # order our tag model alphabetically by the model's name field

    def get_absolute_url(self): # get_absolute_url() method is helpful only for detail pages,for list pages,we'll continue to use reverse() and the url template tag
        return reverse('organizer_tag_detail',kwargs={'slug':self.slug}) # when need to detail of tag,then we call this method,here it returns the url name of tag detail url,pass slug as a argument which needs on url
        # return reverse('organizer_tag_detail',args=(self.slug,)) # here using args in place of kwargs


class Startup(models.Model):
    name = models.CharField(max_length=31, db_index=True) # here applying database indexing
    slug = models.SlugField(max_length=31, unique=True, help_text='A label for URL config.')
    description = models.TextField()
    founded_date = models.DateField('date founded')
    contact = models.EmailField()
    website = models.URLField(max_length=255)
    tags = models.ManyToManyField(Tag) # a startup has multiple tag and a same tag in multiple startup,we could have just as easily created this realtionship in the Tag model by adding an attribute startups.

    def __str__(self):
        return self.name  # for string representation of this class

    class Meta:
        ordering = ['name'] # order lists of startup by name but specify that the latest startup should be the object with most recent founded_date
        get_latest_by = 'founded_date'

    def get_absolute_url(self): # using this method for detail view of startup when it calls
        return reverse('organizer_startup_detail',kwargs={'slug': self.slug}) # pass the parameter self.slug to slug varibale using kwargs dictionary,this parameter needs because urls.py file needs slug
        # return reverse('organizer_startup_detail',args=(self.slug))


class NewsLink(models.Model):
    title = models.CharField(max_length=63)
    pub_date = models.DateField('date published')
    link = models.URLField(max_length=255)
    startup = models.ForeignKey(Startup, on_delete=models.CASCADE) # here one newslink has multiple startup but not reverse, here using one to many relationship on startup and newslink,in one to many field we have to define 'on_delete' where if a field is delete then the releven all field also remove

    def __str__(self):
        return "{}:{}".format(self.startup, self.title) # here show not only title of the link but also which startup object the link is related to

    class Meta:
        verbose_name = 'news article' # this attribute defines the way django displays instances of our models,to display all of instance of this model using verbose_name,normally appending 's' for using verbose_name
        ordering = ['-pub_date']  # using pub_date for ordering,if dash is provide django will order from newest to oldest
        get_latest_by = 'pub_date'  # getting the latest objects using pub_date

    #def get_absolute_url(self): # use this get_absolute url is set to startup get_absolute_url method which define the detail view of startup
       # return self.startup.get_absolute_url() # if i use

organizer/views.py
from django.shortcuts import render, render_to_response
from django.http.response import HttpResponse, Http404, HttpResponseNotFound
from .models import Tag,Startup
from django.template import Context,loader,RequestContext
from django.shortcuts import get_object_or_404,redirect
from .forms import TagForm,StartupForm,NewsLinkForm
from django.views.generic import View


def homepage(request):
    return render(request,'organizer/tag_list.html',{'tag_list':Tag.objects.all()}) # using render automatically use RequestContext object


def tag_list(request):
    queryset = Tag.objects.all()
    context = {
        "tag_list": queryset
    }
    return render(request, "organizer/tag_list.html",context)


def tag_detail(request,slug): # this slug parameter value come from url file when a user try to access a page using slug
    tag = get_object_or_404(Tag, slug__iexact=slug) # using this in place of try catch block,the value of the slug variable came from url passing through the parameter of this function, iexact field use the slug field to be case insensitive,search this row in database with case insensitive format,get() method returns a single object,retrieve the tag using slug
    return render(request,'organizer/tag_detail.html',{'tag':tag}) # using render in place of render_to_response,here using 'template_variable':python_variable


def startup_list(request):
    queryset = Startup.objects.all()
    context = {
        "startup_list": queryset
    }
    return render(request,'organizer/startup_list.html',context)


def startup_detail(request,slug): # this parameter value came from url which one user type
    startup = get_object_or_404(Startup,slug__iexact=slug) # take the startup which one match the user given slug
    context = {
        "startup": startup
    }
    return render(request,'organizer/startup_detail.html',context)
'''
# Pseudocode of create a html form
if HTTP method is POST:
    bind data to form
    if the data is valid:
        create new object from data
        show webpage for new object
    else: # if the data is empty or invalid
        show bound HTML form(with errors)
else: # if the HTTP method is GET or other, but not POST
    show unbound HTML form        

'''


def tag_create(request):  # we don't call this function based method,in place we call Class based tag_create method
    if request.method == 'POST': # django also stores any POST data sent to the server as the POST attribute of the HttpRequest obj
        form = TagForm(request.POST) # POST attribute is a dictionary,which means we can directly use the value to instantiate and bind our form
        if form.is_valid():
            new_tag = form.save() # save the form and store the value in new_tag variable
            return redirect(new_tag) # redirect automatically implement get_absolute_url means which is detail page
        # else: # you don't need to use else option,if the form is invalid then it goes to else and shows the form,here when the data is invalid then return the template and also get request it returns the template,those are identical
         #   return render(request,'organizer/tag_form.html',{'form':form}) # when the form is invalid then show just form page,use render() over render_to_response() because render() uses RequestContext allowing django to inject data into our templates,the use of RequestContext is mandatory because of our use of the csrf_token
    else:
        form = TagForm() # when using get method or PUT/OPTIONS method, just display the form
    return render(request,'organizer/tag_form.html',{'form':form}) # always it returns the temp(form is get/post/invalid


class TagCreate(View): # here create class based view(not generic) in place of function based view
    form_class = TagForm # if we use GCBV(like CreateView) than we can use model directly
    template_name = 'organizer/tag_form.html' # the form_class is the form we will use to create an update this data,template_we will load and render with our form_class

    def get(self,request): # get method is using for display the form,here we use form_class attribute for form to instantiate an unbound form and then render it in our template(with a RequestContext for the csrf_token)
        form = self.form_class()  # form_class is TagForm, if anyone use PUT,OPTIONS method then it display http 405 error(method not found)
        context = {'form': form}
        return render(request,self.template_name,context)

    def post(self,request):  # for post method,which is using for submitting the data
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid(): # if data is valid,we create a new Tag and then redirect to its detail page,redirect implement get_absolute_url method and this method holds detail view
            new_tag = bound_form.save()
            return redirect(new_tag) # redirect to get_absolute_url method which holds detail view,here pass 'new_tag' as a slug parameter to this method,and shows the detail view of this tag
        else: # if the data is invalid,then we display form with errors using dictionary
            return render(request,self.template_name,{'form': bound_form})


class StartupCreate(View): # this class is same as TagCreate class,all documantation right above there
    form_class = StartupForm
    template_name = 'organizer/startup_form.html'

    def get(self,request):
        return render(request,self.template_name,{'form':self.form_class()}) # store the dictionary in template

    def post(self,request):
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            new_startup = bound_form.save() # if form is valid then create a new obj and redirect(means take get_absolute_url method which refers detail view of Startup)
            return redirect(new_startup)
        else:
            return render(request,self.template_name,{'form':bound_form}) # if form is invalid then display the form with error


class NewsLinkCreate(View):  # this one is same as TagCreate class view,all docs write over there
    form_class = NewsLinkForm
    template_name = 'organizer/newslink_form.html'

    def get(self,request):
        return render(request,self.template_name,{'form':self.form_class()})

    def post(self,request):
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid(): # if the form is valid then save it and return it
            new_newslink = bound_form.save() # save it to a new variable
            # return redirect(new_newslink)
            return redirect(new_newslink.startup) # rediret means use get_absolute_url which defines detail view,in detail view we need a slug,there are no slug in newslink,so we pass startup attribute of a newslink which has a slug
        else:
            return render(request,self.template_name,{'form':bound_form})


'''
def homepage(request):
    tag_list = Tag.objects.all() # take all of the tags store into tag_list
    template = loader.get_template('organizer/tag_list.html') # load the templates,passing in a path relative to templates/ directory
    # context = RequestContext(request, {'tag_list': tag_list}) # it's not working django 2.0, sometimes django needs to make changes to the values within the context objects,to enable django to make changes to data that render a template,we must use RequestContext instead of a Context obj
    context = {'tag_list': tag_list} # create a dictionary where passing the tag_list, context = Context({'template_variable':python_variable}),here you don't need to use 'Context' in django 2 version
    output = template.render(context) # render Template with the Context by calling render()
    return HttpResponse(output) # pass text output of the function to HttpResponse
    
    #return render_to_response('organizer/tag_list.html',{'tag_list': Tag.objects.all()}) # here using django shortcut render_to_response in place of all codes which one we commented
'''

'''
def tag_detail(request,slug):
    tag = get_object_or_404(Tag,slug__iexact=slug)  # using this in place of try catch block
    template = loader.get_template('organizer/tag_detail.html')
    # context = RequestContext(request,{'tag':tag}) # if we change the value inside the context we should use RequestContext,RequestContext needs the HttpRequest object
    context = {'tag': tag} # pass the python variable tag to html variable tag using context
    return HttpResponse(template.render(context))

    # return render_to_response('organizer/tag_detail.html',{'tag':tag}) # this is shortcut in place of all codes
    
    # try:
    #    tag = Tag.objects.get(slug__iexact=slug)  # the value of the slug variable came from url passing through the parameter of this function, iexact field use the slug field to be case insensitive,search this row in database with case insensitive format,get() method returns a single object,retrieve the tag using slug
    # except Tag.DoesNotExist: # if a slug is not in database then shows exception(then the tag is not in database)
            # return HttpResponseNotFound('<h1>Tag not found!</h1>') # in production 404 error return automatically
    #        raise Http404
'''


'''
def homepage(request):
    tag_list = Tag.objects.all()
    output = ", ".join([tag.name for tag in tag_list]) # take the all tag name from tag_list and store into a string,delinating each item with comma and space
    return HttpResponse(output)

def homepage(request):
    tag_list = Tag.objects.all()
    html_output = "<html>\n"
    html_output += "<head>\n"
    html_output += " <title>"
    html_output += "Don't Do this!</title>\n"
    html_output += "</head>\n"
    html_output += "<body>\n"
    html_output += " <ul>\n"
    for tag in tag_list:
        html_output += "  <li>"
        html_output += tag.name.title()
        html_output += "<li>\n"
    html_output += "  <ul>\n"
    html_output += "<body>\n"
    html_output += "<html>\n"
    return HttpResponse(html_output)
'''

organizer/templates/organizer/base_organizer.html
{% extends parent_template|default:"base.html" %}

<!--here this template inherits from base.html,and every html file of this organizer directory inherit this 'base_organizer' template -->
<!--developers do not inherit app templates from base template.Instead each app defines an intermediary template,which inherits from the base.This allows apps to define their own behavior.
A template thus first inherits from the app base template,which in turn inherits from the project base template-->

organizer/templates/organizer/newslink_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Link News Article to Startup
{% endblock %}

{% block content %}
<div>
    <div>
        <form action="{% url 'organizer_newslink_create' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Link Article</button>
        </form>
    </div>
</div>

{% endblock %}

organizer/templates/organizer/startup_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %} <!--we changed the inheritance structure to make our lives easier in the long run,it would be prefarable to use a variable and then provide a default to the variable,it allows the Django Controller the possibility of overriding the templates's inheritence scheme without requiring the developer to specify a base template every time this template is used, extends tag must appear as the first tag in the file -->
    <!--the block.super allows us to refer to what exists in the parent block,prints 'Startup Organizer - Jambon Software' -->
 {% block title %}
    {{ block.super }} - {{ startup.name|title }}
 {% endblock %}

 {% block content %}
  <article>
      <h2>{{ startup.name }}</h2> <!--startup is pass from view function -->
      <dl>
          <dt>Date Founded</dt>
            <dd>{{ startup.founded_date}}</dd>  <!--own customize date time format using date filter,ex: "January 18th,2013" -->
            <!--  <dd>{{ startup.founded_date }}</dd> -->
          <dt>Website</dt>
          <dd>{{ startup.website|urlize }}</dd> <!--here using urlize filter which one use nofollow attribute,this attribute telling search engines that spam links are not official -->
          <dt>Contact</dt>
            <dd>{{ startup.contact }}</dd>

          <dt>Tag{{ startup.tags.count|pluralize }}</dt> <!--shows tag or tags,count the tag of a startup -->
           {% for tag in startup.tags.all %} <!--all tags of a startup -->
             <dd> <a href="{{ tag.get_absolute_url }}">{{ tag.name|title }}</a> </dd> <!--using get_absolute method for accessing the detail view of tag,this method defines the detail view in models.py file, show tag name using title filter where first letter of word is capital -->
           {% endfor %}
      </dl>

      {{ startup.description|linebreaks }} <!--using linebreaks filter you don't need to use paragraph tag,create newline after each line -->
      <!--a startup has one newslink but a newslink has multiple startups,here access just one newslink of a startup(one to many relationship) -->
        {% if startup.newslink_set.all %} <!--if the all startup of a newslink is True -->
            <section>
                <h3>Recent News</h3>
                <ul>
                    {% for newslink in startup.newslink_set.all %} <!--print just one newslink,because there are one newslink in a startup but there are multiple startup in one newslink -->
                    <li> <a href="{{ newslink.link }}">{{ newslink.title|title }}</a> </li> <!--show newslink title as a title format -->
                    {% endfor %}
                </ul>
            </section>
        {% endif %}

        {% if startup.blog_posts.all %} <!--a startup has multiple blog posts,and we access all of blog posts of a startup -->
            <section>
                <h3>Blog Post {{ startup.blog_posts.all|pluralize }}</h3>
                <ul>
                    {% for post in startup.blog_posts.all %} <!--show all of posts related to a startup -->
                     <li>
                         <a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a> <!--using get_absolute method for accessing the detail view of post,this method defines the detail view in models.py file -->
                     </li>
                    {% endfor %}
                </ul>
            </section>
        {% endif %}
  </article>
{% endblock %}

organizer/templates/organizer/startup_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Create Startup
{% endblock %}

{% block content %}
<div>
    <div>
        <form action="{% url 'organizer_startup_create' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create Startup</button>
        </form>
    </div>
</div>

{% endblock %}

organizer/templates/organizer/startup_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}
<!--in title shows 'Startup organizer- Startups' -->
{% block title %}
{{ block.super }} - Startups
{% endblock %}

{% block content %}
 <h2>Startup List</h2>
<div>
    <a href="{% url 'organizer_startup_create' %}">Create New Startup</a>
</div>
<ul>
    {% for startup in startup_list %} <!--startup_list template variable come from view function -->
       <li> <!--use the startup_detail link and use startup.slug for identify each startup,on the other hand we can also use get_absolute_url also,slug is a field of Startup model-->
         <!--  <a href="{ u r l 'organizer_startup_detail' startup.slug  %}">{{ startup.name }}</a> --> <!--take the startup.slug as pk for detail view -->
         <a href="{{ startup.get_absolute_url }}">{{ startup.name }}</a>  <!--get_absolute method in Startup model defines the detail view of startup,this method return the slug as kwargs to identify exact startup detail view -->
       </li>
     {% empty %} <!--using empty tag for checking if there are no startup available -->
       <li><em>No Startups Available</em></li>
    {% endfor %}
</ul>
{% endblock %}

organizer/templates/organizer/tag_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Delete Tag
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{{ tag.get_delete_url }}" method="post"> <!--tag is model name and get_delete method is a method for delete -->
                <p>Are you sure want to delete tag {{ tag.name }}</p> <!--tag is model and name is attribute -->
                <a href="{{ tag.get_absolute_url }}">Cancel</a> <!--after cancel then it redirects to get_absolute_url method which means detail view -->
                <button type="submit">Delete Tag</button>
            </form>
        </div>
    </div>
{% endblock %}

organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %} <!--we changed the inheritance structure to make our lives easier in the long run,it would be prefarable to use a variable and then provide a default to the variable,it allows the Django Controller the possibility of overriding the templates's inheritence scheme without requiring the developer to specify a base template every time this template is used, extends tag must appear as the first tag in the file -->

<!--here shows the title like 'Startup organizer-Django' -->
{% block title %}
{{ block.super }} - {{ tag.name|title }}
{% endblock %}

{% block content %}
<!--here using title filter,title filter creates the first letter of tag to capital in each word-->
<h2> {{ tag.name|title }}  </h2> <!--pass particular a tag variable from view function -->

  <!--if the startups of a tag is exist then it shows,'startup_set' is build in django where we can access all startups of a tag -->
  {% if tag.startup_set.all %} <!--here check because a Tag object might not have any Startup objects associated with it -->

  <section>
        <h3>Startup{{ tag.startup_set.count|pluralize }}</h3>
        <p>
        Tag is associate with {{ tag.startup_set.count }}startup{{tag.startup_set.count|pluralize }}.  <!--here using count filter where count the number of all startups connected to the tag,,ex: tag is associate with 12 startups,,in pluralize,if there are multiple startups then shows in plural form rather then singular form,count() is faster than all() filter -->
        </p>
        <h3>Startups</h3>
        <ul>
            <!--list of startups related to a tag,startup_set is build in django(for reverse),access all startups of a tag -->
            {% for startup in tag.startup_set.all %}
                <li> <a href="{{ startup.get_absolute_url }}"> {{ startup.name }}</a> </li> <!--using get_absolute method for accessing the detail view of startup,this method defines the detail view in models.py file, we don't need to use filtering to title in startup -->
            {% endfor %}
        </ul>
    </section>
  {% endif %}

    {% if tag.blog_posts.all %}
        <section>
            <h3>Blog Post{{ tag.blog_posts.count|pluralize }}</h3> <!--Ex: 'Blog Post' or 'Blog Posts' -->
            <ul>
                <!--list of posts related to a tag,'blog_posts' is related name where we can shows all posts of tag -->
                {% for post in tag.blog_posts.all %}
                    <li><a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a></li> <!--using get_absolute method for accessing the detail view of post,this method defines the detail view in models.py file, here using title filter for filtering the title and shows the first letter in capital in each word -->
                {% endfor %}
            </ul>
        </section>
    {% endif %}

    {% if not tag.startup_set.all and not tag.blog_posts.all %}
        <p>This tag is not related to any content</p>
    {% endif %}
{% endblock %}

organizer/templates/organizer/tag_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Create Tag
{% endblock %}

{% block content %}
<div>
   <div>
       <form action="{% url 'organizer_tag_create' %}" method="post"> <!--using form action means what action do in this form,we set u r l name -->
     {% csrf_token %} <!--you can also use form.as_ul or form.as_table -->
     {{ form.as_p }}  <!--this is the django build in form,this shorter rather than loop -->
    <!--  {% for field in form %} --> <!--form is pass from view function,which one use forms.py file -->
     <!--  {{ field.errors }} -->  <!--we call error variables directly which show all of errors of name field,we don't use a loop -->
       <!-- <p> {{ field.label_tag }} --> <!--here we using django build in label in place of label define explicitly -->
        <!-- {{ field }} --> <!--in TagForm the fields are tag,slug -->
       <!--  {% if field.help_text %} --> <!--if there are any help text in field then display it,help text defined in a form,but we are using ModelForm,django will print the help_text attribute we defined in our Tag model -->
        <!--    <span class="helptext">{{ field.help_text }}</span>
         {% endif %} </p>
      {% endfor %} -->
     <button type="submit">Create Tag</button>
 </form>

   </div>
</div>

{% endblock %}


     <!-- {{ form.non_field_errors }} --> <!--we call variables directly which provide the looping behaviour,non_field is build in where shows all error which is not related to field like field combination -->
    <!--  {{ form.name.errors }} --> <!--we call error variables directly which show all of errors of name field,we don't use a loop -->

        <!-- <label for="id_name">Name:</label> -->
        <!-- <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label> -->
       <!-- {{ form.name.label_tag }} --> <!--here we using django build in label in place of label define explicitly -->
       <!--  {{ form.name }}--> <!--here display previous form name if the user submitted invalid data,we don't need to use if,else condition,django automatically do this -->
        <!-- <input id="id_name" maxlength="31" name="name" type="text"/> -->


     <!-- {{ form.slug.errors }} --> <!--we display all of slug errors using one variable in place of using loop,errors is build in python function -->

        <!-- <label for="id_slug">Slug:</label> -->
        <!-- <label for="{{ form.slug.id_for_label }}">{{ form.slug.label }}</label> --> <!--using django build in label for slug in place of explicitly define slug label -->
       <!--  {{ form.slug.label_tag }} --> <!--shortening the code for slug label -->
       <!--   {{ form.slug }} --> <!--if the user submit wrong or invalid slug then django shows the previous slug value which one user submitted,we don't need to create if else condition,django automatically do this -->
        <!-- <input id="id_slug" maxlength="31" name="slug" type="text"/> -->

        <!-- <span class="helptext"> --> <!--help text defined in a form,but we are using ModelForm,django will print the help_text attribute we defined in our Tag model -->
        <!--     {{ form.slug_help_text }} --> <!--here shows slug_help_text if you submit a invalid input,you don't need to use if,else statement -->
       <!--  </span> -->

<!-- {% if form.non_field_errors %} --> <!-- if there are non field errors means any error not associated with field like an error that arises from a combination of fields or from the form itself -->
 <!-- <ul class="custom_error_list"> --> <!--non_field_errors is build in python method -->
     <!-- {% for error in form.non_field_errors %}
        <li><em>{{ error }}</em></li>
      {% endfor %}
  </ul>
{% endif %} -->


<!-- {% if form.name.errors %} --> <!--if there are errors in name attribute in form field,here error is build in python function -->
  <!-- <ul class="custom_error_list"> -->
    <!--  {% for error in form.name.errors %} --> <!--display all errors  -->
       <!--  <li><em>{{ error }}</em></li>
      {% endfor %}
  </ul>
{% endif %} -->

<!-- {% if form.slug.errors %} --> <!--if there are errors in slug attribute in form -->
 <!-- <ul class="custom_error_list">
      {% for error in form.slug.errors %} --> <!--display all errors  -->
       <!--  <li><em>{{ error }}</em></li>
      {% endfor %}
  </ul>
  {% endif %} -->


<!-- {% if form.name.value %} --> <!--if the user submits invalid data,the form will now provide the name value the user submitted,django provides the conditional checks for values -->
<!--   <input id="id_name" maxlength="31" --> <!--here using if condition to provide submitted data back to the user when redisplaying forms -->
<!--   name="name" type="text" value="{{ form.name.value }}"/>
{% else %}
   <input id="id_name" maxlength="31" --> <!--normally it shows empty form -->
 <!--  name="name" type="text"/>
{% endif %} -->

<!-- {% if form.slug.value %} --> <!--if the user submits invalid data,the form will now provide the slug value the user submitted -->
<!--   <input id="id_slug" maxlength="31"
   name="slug" type="text" value="{{ form.slug.value }}"/>
{% else %}
   <input id="id_slug" maxlength="31" --> <!--normally it shows empty form -->
 <!--  name="slug" type="text"/>
{% endif %} -->